# Generated by Django 5.1.4 on 2024-12-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_advice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advice',
            table=None,
        ),
    ]
