# Generated by Django 5.1.4 on 2025-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_emotion_healthyactivity_hobby_householdtask_meals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='description',
        ),
    ]
