# Generated by Django 5.1.4 on 2025-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_alter_sleepquality_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='emotions',
            field=models.ManyToManyField(blank=True, null=True, to='entries.emotion'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='healthy_activities',
            field=models.ManyToManyField(blank=True, null=True, to='entries.healthyactivity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, to='entries.hobby'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='household_tasks',
            field=models.ManyToManyField(blank=True, null=True, to='entries.householdtask'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='meals',
            field=models.ManyToManyField(blank=True, null=True, to='entries.meals'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='personal_growth',
            field=models.ManyToManyField(blank=True, null=True, to='entries.personalgrowth'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='productivity',
            field=models.ManyToManyField(blank=True, null=True, to='entries.productivity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sleep_quality',
            field=models.ManyToManyField(blank=True, null=True, to='entries.sleepquality'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='social_activities',
            field=models.ManyToManyField(blank=True, null=True, to='entries.socialactivity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weather',
            field=models.ManyToManyField(blank=True, null=True, to='entries.weather'),
        ),
    ]
