# Generated by Django 5.1.4 on 2024-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField()),
                ('date', models.DateField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'Entries',
            },
        ),
    ]
