# Generated by Django 5.1.4 on 2025-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
