# Generated by Django 5.1.4 on 2025-01-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='exempted_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
